### ISSUE TITLE
I can add some LLD design in this repo

### ISSUE THREAD

**Issue by codeimmortal** [thesaltree/low-level-design-golang#1]
I was thinking is there is something out there, if you don't mind. I can add some lld here ,I don't want to create one more repo which do same thing.

**Comment by thesaltree** [comment]
@codeimmortal,  thank you for your interest in contributing more solutions. I was planning to add the following topics next:

- Meeting scheduler design
- ATM design
- Car rental system design

If any of these topics interest you, we can discuss the problem requirements further. Thank you again for your contribution!

**Comment by codeimmortal** [comment]
Meeting scheduler design , i can take. Let me know its fine with you. If yes, i will add new issue with it and all detail there.
